/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sharing_travel_social_neyworks_fe;

import org.gradle.api.Project;
import org.gradle.api.Plugin;

/**
 * A simple 'hello world' plugin.
 */
public class Sharing_travel_social_neyworks_fePlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a task
        project.getTasks().register("greeting", task -> {
            task.doLast(s -> System.out.println("Hello from plugin 'sharing_travel_social_neyworks_fe.greeting'"));
        });
    }
}
